apiVersion: v1
kind: Service
metadata:
  name: git-pull-request-dashboard
  namespace: automation
  labels:
    app: git-pull-request-dashboard
spec:
  selector:
    app: git-pull-request-dashboard
  ports:
    - name: http
      port: 80
      targetPort: http
