name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
    files:
      - "src/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Build
        run: |
          export VITE_GITHUB_API_URL=$VITE_GITHUB_API_URL
          npm ci
          npm run build
        env:
          CI: true
          VITE_GITHUB_API_URL: "https://api.github.com"
      - name: Update HTML Links
        run: |
          sed -i 's|href="/|href="|g' dist/index.html
          sed -i 's|src="/|src="|g' dist/index.html
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
